version: 2.1
jobs:
  test:
    docker:
      - image: reasonnative/esy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: esy install
      - run:
          name: Build
          command: esy build
      - run:
          name: Test
          command: esy test --debug-backtrace
workflows:
  version: 2.1
  test:
    jobs:
      - test
